server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-test/config-repository.git
        native:
          search-locations: file://${user.home}/IdeaProjects/cloud/config-repository
  # Messaging Service
  rabbitmq:
    host: 127.0.0.1
    port: 5673
    username: guest
    password: guest
