server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-test/config-repository.git
        native:
          search-locations: file://${user.home}/IdeaProjects/config-repository
